<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="6.1700" tests="9" failures="4">
  <testsuite name="Root Suite" timestamp="2020-06-04T04:22:29" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="COONNECT TO DATABASE" timestamp="2020-06-04T04:22:29" tests="1" file="D:\Projects\node-python\test\myTrips.js" time="2.2870" failures="0">
    <testcase name="COONNECT TO DATABASE connecting to database" time="2.2870" classname="connecting to database">
    </testcase>
  </testsuite>
  <testsuite name="CHECK FUNCTION =&gt; addUser" timestamp="2020-06-04T04:22:31" tests="4" file="D:\Projects\node-python\test\myTrips.js" time="2.7040" failures="2">
    <testcase name="CHECK FUNCTION =&gt; addUser add email" time="2.0810" classname="add email">
    </testcase>
    <testcase name="CHECK FUNCTION =&gt; addUser Add duplicate user" time="0.3030" classname="Add duplicate user">
      <failure message="MongoError: E11000 duplicate key error collection: testingDatabase.Users index: email_1 dup key: { email: &quot;nimala11@gmail.com&quot; }" type="Error"><![CDATA[Error: MongoError: E11000 duplicate key error collection: testingDatabase.Users index: email_1 dup key: { email: "nimala11@gmail.com" }
    at D:\Projects\node-python\api\models\mongoose.js:601:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="CHECK FUNCTION =&gt; addUser Adding Number insted string" time="0.3160" classname="Adding Number insted string">
    </testcase>
    <testcase name="CHECK FUNCTION =&gt; addUser add array" time="0.0040" classname="add array">
      <failure message="ValidationError: email: Cast to String failed for value &quot;[ &apos;nimala31@gmail.com&apos;, &apos;nimala21@gmail.com&apos; ]&quot; at path &quot;email&quot;" type="Error"><![CDATA[Error: ValidationError: email: Cast to String failed for value "[ 'nimala31@gmail.com', 'nimala21@gmail.com' ]" at path "email"
    at D:\Projects\node-python\api\models\mongoose.js:601:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="CHECK FUNCTION =&gt; checkUser" timestamp="2020-06-04T04:22:34" tests="4" file="D:\Projects\node-python\test\myTrips.js" time="1.1790" failures="2">
    <testcase name="CHECK FUNCTION =&gt; checkUser check avaulable user =&gt; should pass" time="0.3300" classname="check avaulable user =&gt; should pass">
    </testcase>
    <testcase name="CHECK FUNCTION =&gt; checkUser check avaulable user =&gt; should fail" time="0.2860" classname="check avaulable user =&gt; should fail">
      <failure message="expected true to equal false" type="AssertionError"><![CDATA[AssertionError: expected true to equal false
    at D:\Projects\node-python\test\myTrips.js:96:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="CHECK FUNCTION =&gt; checkUser check not avaulable user =&gt; should pass" time="0.2770" classname="check not avaulable user =&gt; should pass">
    </testcase>
    <testcase name="CHECK FUNCTION =&gt; checkUser check not avaulable user =&gt; should fail" time="0.2860" classname="check not avaulable user =&gt; should fail">
      <failure message="expected false to equal true" type="AssertionError"><![CDATA[AssertionError: expected false to equal true
    at D:\Projects\node-python\test\myTrips.js:118:20
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>